# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'done.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(0, 0, 791, 461))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("mik.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.mik = QtWidgets.QPushButton(self.centralwidget)
        self.mik.setGeometry(QtCore.QRect(430, 470, 321, 61))
        self.mik.setObjectName("mik")
        self.boot = QtWidgets.QPushButton(self.centralwidget)
        self.boot.setGeometry(QtCore.QRect(80, 470, 321, 61))
        self.boot.setObjectName("boot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.mik.clicked.connect(self.show_mik)
        self.boot.clicked.connect(self.show_boot)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mik.setText(_translate("MainWindow", "mik"))
        self.boot.setText(_translate("MainWindow", "boot"))

    def show_mik(self):
        self.photo.setPixmap(QtGui.QPixmap("yep/mik.jpg"))

    def show_boot(self):
        self.photo.setPixmap(QtGui.QPixmap("yep/boot.jpg"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
